import pandas as pd
import os
import re
from OSMPythonTools.overpass import Overpass
import geopandas as gpd
from shapely.geometry import Polygon, LineString, Point
from timeit import default_timer as timer

# # SF Bay
# West = '-122.6126'
# North = '38.2182'
# East = '-121.7378'
# South = '37.2066'

# Puget Sound
West = '-122.755863'
North = '48.1162201'
East = '-121.7631845'
South = '46.8555182'

overpass = Overpass()

filename = 'map/station_list_2023.csv'
# filename = 'map/station_list_2023_SF.csv'

print('Loading in station data')

df = pd.read_csv(filename, dtype={'station_index': str})

df_station_locations = df[['station_index', 'latitude', 'longitude']].drop_duplicates()
df_station_locations['trunc_lat'] = df_station_locations['latitude'].round(1)
df_station_locations['trunc_lon'] = df_station_locations['longitude'].round(1)

trunc_list = list(zip(df_station_locations['trunc_lat'], df_station_locations['trunc_lon']))

for i in trunc_list:
    center_lat = i[0]
    center_lon = i[1]

    station_filter = (df_station_locations['trunc_lat'] == center_lat) & (
                df_station_locations['trunc_lon'] == center_lon)

    df_station_locations[station_filter].groupby(['trunc_lat', 'trunc_lon']).agg({'station_index': pd.Series.nunique})
    West = center_lon - 0.3
    North = center_lat + 0.3
    East = center_lon + 0.3
    South = center_lat - 0.3

    print('Bounding Box: ', West, North, East, South)


    # # Examples

    # api = Api()
    # way = api.query('way/5887599')
    # way.tag('building')
    # result = overpass.query('way["name"="Stephansdom"]; out body;')
    # result = overpass.query('way["name"="Ballard Bridge"]; out body;')

    # Motorways within the Purple Air bounding box
    print('Querying OpenStreetMap')
    # OPquery = 'way["highway"="motorway"](' + South + ',' + West + ',' + North + ',' + East + '); out geom;'
    OPquery = f'way["highway"="motorway"]({South}, {West}, {North}, {East}); out geom;'
    result = overpass.query(OPquery)
    # OPqueryT = 'way["highway"="trunk"](' + South + ',' + West + ',' + North + ',' + East + '); out geom;'
    OPqueryT = f'way["highway"="trunk"]({South}, {West}, {North}, {East}); out geom;'
    result_t = overpass.query(OPqueryT)

    motorways = dict()

    for e in result.elements():
        motorways[e.id()] = {
            'type': e.type(),
            'tags': e.tags(),
            'geometry': e.geometry()
        }

    for e in result_t.elements():
        motorways[e.id()] = {
            'type': e.type(),
            'tags': e.tags(),
            'geometry': e.geometry()
        }

    interstates = dict()

    print('Filtering for Interstates')

    # Puget Sound Filter
    # for id, item in motorways.items():
    #     ref = item['tags'].get('ref', '')
    #     if (not re.search('I\s*-?\s*5', ref) is None):
    #         interstates[id] = item
    #
    #     if (not re.search('I\s*-?\s*90', ref) is None):
    #         interstates[id] = item
    #
    #     if (not re.search('520', ref) is None):
    #         interstates[id] = item
    #         # print(id, item['tags']['ref'], item['tags'].get('maxspeed'), item['geometry'])

    # SF Bay non-filter
    for id, item in motorways.items():
        ref = item['tags'].get('ref', '')
        interstates[id] = item

    # The simplest way to get all data from a bounding box is to explicitly state so (Link):

    # nwr(51.477,-0.001,51.478,0.001);
    # out;

    # Here (51.477,-0.001,51.478,0.001) represents the bounding box. The order of the edges is always the same:

    #     51.477 is the latitude of the southern edge.
    #     -0.001 is the longitude of the western edge.
    #     51.478 is the latitude of the norther edge.
    #     0.001 is the longitude of the eastern edge.

    # [(-122.755863 w, 48.1162201 n),(-121.7631845 e,46.8555182 s)] # all of puget sound
    # nwr(46.8555182, -122.755863, 48.1162201, -121.7631845)


    # https://github.com/mocnik-science/osm-python-tools/blob/master/docs/element.md

    # station: (47.614223, -122.16950)
    # segment: {"coordinates": [[-122.322639, 47.65701], [-122.322601, 47.656181], [-122.322585, 47.65568], [-122.322668, 47.651159], [-122.322699, 47.64922], [-122.322709, 47.64868], [-122.322751, 47.648064], [-122.322774, 47.647758], [-122.322893, 47.646707]], "type": "LineString"}
    # ESRI:103563 https://epsg.io/103563

    # This has been generated by the overpass-turbo wizard.
    # The original search was:
    # "(highway=primary or highway=secondary) and type:way :"
    #
    # [out:json][timeout:25];
    # // gather results
    # (
    #   way["highway"="motorway"](47.6025750415702,-122.36899967196507,47.68376562248428,-122.2345888138108);
    # );
    # // print results
    # out geom;

    print('Picking world shape')

    segments_df = gpd.GeoSeries(

        [
            LineString([[-122.322639, 47.65701], [-122.322601, 47.656181], [-122.322585, 47.65568], [-122.322668, 47.651159], [-122.322699, 47.64922], [-122.322709, 47.64868], [-122.322751, 47.648064], [-122.322774, 47.647758], [-122.322893, 47.646707]])
        ],
        crs='EPSG:4326'
    )

    # segments_df = segments_df.to_crs('EPSG:6596') # Northern WA
    # segments_df = segments_df.to_crs('EPSG:7131') # SF Bay
    # Plug this into google maps to see it: from 47.65701, -122.322639 to 47.646707, -122.322893
    #
    # point = Point(-122.16950, 47.614223)
    # stations_df = gpd.GeoDataFrame({'geometry': [point,]}, crs='EPSG:4326')
    # stations_df = stations_df.to_crs('EPSG:6596')
    #
    # segments_df.distance(stations_df)/1000.0

    station_distance_df = dict()

    print('Calculating distances')

    for i, row in df_station_locations[station_filter].iterrows():
        start = timer()

        station_index = row['station_index']

        # print('station: ' + station_index)

        station_distance_df[station_index] = list()

        point = Point(row['longitude'], row['latitude'])
        stations_gdf = gpd.GeoDataFrame({'geometry': [point,]}, crs='EPSG:4326')
        # stations_gdf = stations_gdf.to_crs('EPSG:6596') # Northern WA
        stations_gdf = stations_gdf.to_crs('EPSG:7131') # SF Bay

        for way, item in interstates.items():
            #print(way, item['geometry']['coordinates'])
            try:
                segments_df = gpd.GeoSeries(

                    [
                        LineString(item['geometry']['coordinates'])
                    ],
                    crs='EPSG:4326'
                )

                # segments_df = segments_df.to_crs('EPSG:6596') # Northern WA
                segments_df = segments_df.to_crs('EPSG:7131')  # SF Bay
                dist = segments_df.distance(stations_gdf)[0]/1000.0

                station_distance_df[station_index].append(
                    {
                        'way': way,
                        'distance': dist
                    }

                )
            except:
                pass
        end = timer()
        print('station: ' + station_index + ' | calc time: ', end - start,'s')
    def f(x):
        return(x['distance'])

    # sorted(station_distance_df['3225'], key=f)[0] # example

    nearest = dict()

    print('Filtering for nearest way')

    try:
        for i, item in station_distance_df.items():
            # print(i, item)
            y = sorted(station_distance_df[i], key=f)[0]
            nearest[i] = y
    except:
        for i, item in station_distance_df.items():
            nearest[i] = ''
    # for i, item in nearest.items():
        # print(i, item['way'], item['distance'])

    nearest_df = pd.DataFrame.from_dict(nearest, orient='index').reset_index()
    nearest_df = nearest_df.rename(columns={'index':'station_index'})

    merged_df = df.merge(nearest_df, how='left', on='station_index')

merged_df['freeway_adjacent_0_5'] = merged_df['distance'] < .5
merged_df['freeway_adjacent_1_0'] = merged_df['distance'] < 1
merged_df['freeway_adjacent_1_5'] = merged_df['distance'] < 1.5
merged_df['freeway_adjacent_2_0'] = merged_df['distance'] < 2
merged_df['freeway_adjacent_2_5'] = merged_df['distance'] < 2.5
merged_df['freeway_adjacent_3_0'] = merged_df['distance'] < 3
merged_df['freeway_adjacent_3_5'] = merged_df['distance'] < 3.5
merged_df['freeway_adjacent_4_0'] = merged_df['distance'] < 4


# outfile = 'map/station_distance_2023-SF.csv'
outfile = 'map/station_distance-2023.csv'

print('writing ' + outfile)

merged_df.to_csv(outfile)
# print('Plotting AQI')
#
#
# plt.figure(figsize=(16,12))
# sns.scatterplot(data=merged_df[merged_df['date'] == '2020-10-31'], x='distance', y='pm2_5_AVG')
#
# plt.savefig('distance.png')